[package]
name = "rustrover_ai_plugin"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
nih_plug = { git = "https://github.com/robbert-vdh/nih-plug" }
dsp-core = { path = "../dsp-core" }

[profile.release]
lto = true
codegen-units = 1
